// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request/request.proto

/*
Package request is a generated protocol buffer package.

package request defines request datatypes

It is generated from these files:
	request/request.proto

It has these top-level messages:
	Empty
	Status
*/
package request

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status struct {
	Callback string `protobuf:"bytes,1,opt,name=callback" json:"callback,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Status) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "request.Empty")
	proto.RegisterType((*Status)(nil), "request.Status")
}

func init() { proto.RegisterFile("request/request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x12, 0x3b, 0x17, 0xab, 0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x92, 0x0a, 0x17, 0x5b, 0x70, 0x49, 0x62,
	0x49, 0x69, 0xb1, 0x90, 0x14, 0x17, 0x47, 0x72, 0x62, 0x4e, 0x4e, 0x52, 0x62, 0x72, 0xb6, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0xef, 0x64, 0x1c, 0x65, 0x98, 0x9e, 0x59, 0x92, 0x51,
	0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x5f, 0x9a, 0x94, 0x9c, 0x93, 0x58, 0x9a, 0x97, 0x9c, 0x51,
	0x90, 0x98, 0xa2, 0x5f, 0x90, 0x99, 0x57, 0x90, 0x9f, 0x99, 0x57, 0xa2, 0x0f, 0xb6, 0x21, 0xa9,
	0x34, 0x0d, 0x66, 0x65, 0x12, 0x1b, 0x58, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xde,
	0x2e, 0xf3, 0x8c, 0x00, 0x00, 0x00,
}
