// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request/request.proto

package request // import "github.com/ubclaunchpad/pinpoint/protobuf/request"

/*
package request defines request datatypes
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_329c7a3b0d683d36, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Status struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_329c7a3b0d683d36, []int{1}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

type CreateAccount struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccount) Reset()         { *m = CreateAccount{} }
func (m *CreateAccount) String() string { return proto.CompactTextString(m) }
func (*CreateAccount) ProtoMessage()    {}
func (*CreateAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_329c7a3b0d683d36, []int{2}
}
func (m *CreateAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccount.Unmarshal(m, b)
}
func (m *CreateAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccount.Marshal(b, m, deterministic)
}
func (dst *CreateAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccount.Merge(dst, src)
}
func (m *CreateAccount) XXX_Size() int {
	return xxx_messageInfo_CreateAccount.Size(m)
}
func (m *CreateAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccount proto.InternalMessageInfo

func (m *CreateAccount) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Verify struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Verify) Reset()         { *m = Verify{} }
func (m *Verify) String() string { return proto.CompactTextString(m) }
func (*Verify) ProtoMessage()    {}
func (*Verify) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_329c7a3b0d683d36, []int{3}
}
func (m *Verify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verify.Unmarshal(m, b)
}
func (m *Verify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verify.Marshal(b, m, deterministic)
}
func (dst *Verify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verify.Merge(dst, src)
}
func (m *Verify) XXX_Size() int {
	return xxx_messageInfo_Verify.Size(m)
}
func (m *Verify) XXX_DiscardUnknown() {
	xxx_messageInfo_Verify.DiscardUnknown(m)
}

var xxx_messageInfo_Verify proto.InternalMessageInfo

func (m *Verify) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Verify) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Login struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_329c7a3b0d683d36, []int{4}
}
func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (dst *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(dst, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "request.Empty")
	proto.RegisterType((*Status)(nil), "request.Status")
	proto.RegisterType((*CreateAccount)(nil), "request.CreateAccount")
	proto.RegisterType((*Verify)(nil), "request.Verify")
	proto.RegisterType((*Login)(nil), "request.Login")
}

func init() { proto.RegisterFile("request/request.proto", fileDescriptor_request_329c7a3b0d683d36) }

var fileDescriptor_request_329c7a3b0d683d36 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3f, 0x4b, 0x04, 0x31,
	0x10, 0xc5, 0xb9, 0xd3, 0xdd, 0x3b, 0x07, 0x6c, 0x82, 0xc2, 0x62, 0x25, 0xa9, 0xac, 0x2e, 0xe8,
	0x55, 0x96, 0x2a, 0x76, 0x56, 0x8a, 0x16, 0x76, 0x93, 0x5c, 0xee, 0x12, 0xd8, 0xfc, 0x31, 0x99,
	0x20, 0xfb, 0xed, 0xc5, 0xb8, 0x2b, 0x5a, 0x6c, 0x35, 0xef, 0xfd, 0x60, 0xde, 0x83, 0x07, 0xe7,
	0x49, 0x7f, 0x14, 0x9d, 0x49, 0x8c, 0x77, 0x13, 0x53, 0xa0, 0xc0, 0x56, 0xa3, 0xe5, 0x2b, 0x68,
	0x1e, 0x5d, 0xa4, 0x81, 0xaf, 0xa1, 0x7d, 0x21, 0xa4, 0x92, 0xf9, 0x2b, 0x9c, 0x3e, 0x24, 0x8d,
	0xa4, 0xef, 0x94, 0x0a, 0xc5, 0x13, 0x3b, 0x83, 0x46, 0x3b, 0xb4, 0x7d, 0xb7, 0xb8, 0x5c, 0x5c,
	0x9d, 0x3c, 0xff, 0x18, 0xc6, 0xe0, 0xd8, 0xa3, 0xd3, 0xdd, 0xb2, 0xc2, 0xaa, 0xd9, 0x05, 0xac,
	0x23, 0xe6, 0xfc, 0x19, 0xd2, 0xae, 0x3b, 0xaa, 0xfc, 0xd7, 0xf3, 0x1b, 0x68, 0xdf, 0x74, 0xb2,
	0xfb, 0x61, 0x3e, 0xcf, 0x60, 0x36, 0x53, 0xde, 0xb7, 0xe6, 0xb7, 0xd0, 0x3c, 0x85, 0x83, 0xf5,
	0x33, 0x2f, 0x7f, 0xeb, 0x96, 0xff, 0xeb, 0xee, 0xb7, 0xef, 0xd7, 0x07, 0x4b, 0xa6, 0xc8, 0x8d,
	0x0a, 0x4e, 0x14, 0xa9, 0x7a, 0x2c, 0x5e, 0x99, 0x88, 0x3b, 0x11, 0xad, 0x8f, 0xc1, 0x7a, 0x12,
	0x75, 0x0b, 0x59, 0xf6, 0xd3, 0x38, 0xb2, 0xad, 0x64, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x2a,
	0x1f, 0x25, 0x50, 0x36, 0x01, 0x00, 0x00,
}
