# docker-compose configuration for spinning up a monitoring environment

version: '3.6'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.5.0
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601

  filebeat:
    depends_on:
      - elasticsearch
      - kibana
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:6.5.0
    links:
      - "kibana:kibana"
      - "elasticsearch:elasticsearch"
    restart: always
    volumes:
      - ../tmp:/var/log
      - type: bind
        source: ./conf/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
