// Code generated by ifacemaker. DO NOT EDIT.

package database

import (
	"github.com/ubclaunchpad/pinpoint/core/model"
)

// DBClient wraps the AWS DynamoDB database API
type DBClient interface {
	// AddNewUser creates a new user in the database
	AddNewUser(u *model.User, e *model.EmailVerification) error
	// GetUser returns a user from the database with the given email
	GetUser(email string) (*model.User, error)
	// DeleteUser deletes a user from the database with the given email
	DeleteUser(email string) error
	// GetEmailVerification returns a pending email verification from the database
	// with the given email
	GetEmailVerification(hash string) (*model.EmailVerification, error)
	// AddNewClub creates a new club in the database with a user (creator) associated to it
	AddNewClub(c *model.Club, cu *model.ClubUser) error
	// GetClub returns a club with the given id
	GetClub(id string) (*model.Club, error)
	// GetAllClubUsers returns a list of ClubUsers associated with a club
	GetAllClubUsers(id string) ([]*model.ClubUser, error)
	// DeleteClub deletes a club from the database with the given id
	DeleteClub(id string) error
}
