// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pinpoint.proto

package pinpoint

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import request "github.com/ubclaunchpad/pinpoint/protobuf/request"
import response "github.com/ubclaunchpad/pinpoint/protobuf/response"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoreClient interface {
	GetStatus(ctx context.Context, in *request.Status, opts ...grpc.CallOption) (*response.Status, error)
	Handshake(ctx context.Context, in *request.Empty, opts ...grpc.CallOption) (*response.Empty, error)
	// clubs
	CreateEvent(ctx context.Context, in *request.CreateEvent, opts ...grpc.CallOption) (*response.Message, error)
	SubmitEvent(ctx context.Context, in *request.SubmitEvent, opts ...grpc.CallOption) (*response.Message, error)
	// users
	CreateAccount(ctx context.Context, in *request.CreateAccount, opts ...grpc.CallOption) (*response.Message, error)
	Verify(ctx context.Context, in *request.Verify, opts ...grpc.CallOption) (*response.Message, error)
	Login(ctx context.Context, in *request.Login, opts ...grpc.CallOption) (*response.Message, error)
}

type coreClient struct {
	cc *grpc.ClientConn
}

func NewCoreClient(cc *grpc.ClientConn) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) GetStatus(ctx context.Context, in *request.Status, opts ...grpc.CallOption) (*response.Status, error) {
	out := new(response.Status)
	err := c.cc.Invoke(ctx, "/pinpoint.Core/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) Handshake(ctx context.Context, in *request.Empty, opts ...grpc.CallOption) (*response.Empty, error) {
	out := new(response.Empty)
	err := c.cc.Invoke(ctx, "/pinpoint.Core/Handshake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateEvent(ctx context.Context, in *request.CreateEvent, opts ...grpc.CallOption) (*response.Message, error) {
	out := new(response.Message)
	err := c.cc.Invoke(ctx, "/pinpoint.Core/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) SubmitEvent(ctx context.Context, in *request.SubmitEvent, opts ...grpc.CallOption) (*response.Message, error) {
	out := new(response.Message)
	err := c.cc.Invoke(ctx, "/pinpoint.Core/SubmitEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateAccount(ctx context.Context, in *request.CreateAccount, opts ...grpc.CallOption) (*response.Message, error) {
	out := new(response.Message)
	err := c.cc.Invoke(ctx, "/pinpoint.Core/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) Verify(ctx context.Context, in *request.Verify, opts ...grpc.CallOption) (*response.Message, error) {
	out := new(response.Message)
	err := c.cc.Invoke(ctx, "/pinpoint.Core/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) Login(ctx context.Context, in *request.Login, opts ...grpc.CallOption) (*response.Message, error) {
	out := new(response.Message)
	err := c.cc.Invoke(ctx, "/pinpoint.Core/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServer is the server API for Core service.
type CoreServer interface {
	GetStatus(context.Context, *request.Status) (*response.Status, error)
	Handshake(context.Context, *request.Empty) (*response.Empty, error)
	// clubs
	CreateEvent(context.Context, *request.CreateEvent) (*response.Message, error)
	SubmitEvent(context.Context, *request.SubmitEvent) (*response.Message, error)
	// users
	CreateAccount(context.Context, *request.CreateAccount) (*response.Message, error)
	Verify(context.Context, *request.Verify) (*response.Message, error)
	Login(context.Context, *request.Login) (*response.Message, error)
}

func RegisterCoreServer(s *grpc.Server, srv CoreServer) {
	s.RegisterService(&_Core_serviceDesc, srv)
}

func _Core_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.Status)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinpoint.Core/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetStatus(ctx, req.(*request.Status))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinpoint.Core/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).Handshake(ctx, req.(*request.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.CreateEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinpoint.Core/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateEvent(ctx, req.(*request.CreateEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_SubmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.SubmitEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).SubmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinpoint.Core/SubmitEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).SubmitEvent(ctx, req.(*request.SubmitEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.CreateAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinpoint.Core/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateAccount(ctx, req.(*request.CreateAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.Verify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinpoint.Core/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).Verify(ctx, req.(*request.Verify))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.Login)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinpoint.Core/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).Login(ctx, req.(*request.Login))
	}
	return interceptor(ctx, in, info, handler)
}

var _Core_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pinpoint.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Core_GetStatus_Handler,
		},
		{
			MethodName: "Handshake",
			Handler:    _Core_Handshake_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _Core_CreateEvent_Handler,
		},
		{
			MethodName: "SubmitEvent",
			Handler:    _Core_SubmitEvent_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _Core_CreateAccount_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Core_Verify_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Core_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pinpoint.proto",
}

func init() { proto.RegisterFile("pinpoint.proto", fileDescriptor_pinpoint_eabf21ab2baa50d4) }

var fileDescriptor_pinpoint_eabf21ab2baa50d4 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3d, 0x4b, 0x43, 0x31,
	0x14, 0x86, 0x8b, 0x68, 0xb1, 0x47, 0x6c, 0xf5, 0xe0, 0x07, 0x64, 0xec, 0x2c, 0xa9, 0xe8, 0xe2,
	0xe0, 0x22, 0xa5, 0xe8, 0xa0, 0x53, 0xc1, 0x3d, 0xad, 0xc7, 0x1a, 0xa4, 0x49, 0x4c, 0x4e, 0x84,
	0xfb, 0xcf, 0x1d, 0x85, 0x9b, 0xfb, 0x11, 0x2e, 0x99, 0x92, 0xf3, 0xe4, 0x7d, 0x12, 0x78, 0x03,
	0x53, 0xa7, 0x8d, 0xb3, 0xda, 0xb0, 0x74, 0xde, 0xb2, 0xc5, 0xe3, 0x76, 0x16, 0x97, 0x9e, 0x7e,
	0x22, 0x05, 0x5e, 0x34, 0x6b, 0x0a, 0x88, 0x6b, 0x4f, 0xc1, 0x59, 0x13, 0x68, 0xd1, 0x6e, 0xd2,
	0xc1, 0xdd, 0xdf, 0x01, 0x1c, 0x2e, 0xad, 0x27, 0xbc, 0x85, 0xc9, 0x33, 0xf1, 0x9a, 0x15, 0xc7,
	0x80, 0x33, 0xd9, 0xea, 0x09, 0x88, 0x33, 0xd9, 0x79, 0x89, 0xcc, 0x47, 0x28, 0x61, 0xf2, 0xa2,
	0xcc, 0x47, 0xf8, 0x52, 0xdf, 0x84, 0xd3, 0xce, 0x58, 0xed, 0x1d, 0x57, 0x62, 0xd6, 0x0b, 0x35,
	0x98, 0x8f, 0xf0, 0x01, 0x4e, 0x96, 0x9e, 0x14, 0xd3, 0xea, 0x97, 0x0c, 0xe3, 0x45, 0x67, 0x64,
	0x54, 0x9c, 0xf7, 0xde, 0x1b, 0x85, 0xa0, 0x76, 0x94, 0xcc, 0x75, 0xdc, 0xec, 0x35, 0x0f, 0xcd,
	0x8c, 0x96, 0xcd, 0x47, 0x38, 0x4d, 0xb7, 0x3f, 0x6d, 0xb7, 0x36, 0x1a, 0xc6, 0xab, 0xc1, 0xab,
	0x0d, 0x2f, 0xdb, 0x12, 0xc6, 0xef, 0xe4, 0xf5, 0x67, 0x95, 0x15, 0x92, 0x40, 0x39, 0x7f, 0x03,
	0x47, 0xaf, 0x76, 0xa7, 0x4d, 0xd6, 0x46, 0x3d, 0x17, 0xd3, 0x9b, 0x71, 0xfd, 0x03, 0xf7, 0xff,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xde, 0xb2, 0x1e, 0xed, 0xcd, 0x01, 0x00, 0x00,
}
