// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/models.proto

package models // import "github.com/ubclaunchpad/pinpoint/protobuf/models"

/*
package model defines model datatypes
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Verified             bool     `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type Club struct {
	ClubID               string   `protobuf:"bytes,1,opt,name=clubID,proto3" json:"clubID,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Club) Reset()         { *m = Club{} }
func (m *Club) String() string { return proto.CompactTextString(m) }
func (*Club) ProtoMessage()    {}
func (*Club) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{1}
}
func (m *Club) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Club.Unmarshal(m, b)
}
func (m *Club) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Club.Marshal(b, m, deterministic)
}
func (dst *Club) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Club.Merge(dst, src)
}
func (m *Club) XXX_Size() int {
	return xxx_messageInfo_Club.Size(m)
}
func (m *Club) XXX_DiscardUnknown() {
	xxx_messageInfo_Club.DiscardUnknown(m)
}

var xxx_messageInfo_Club proto.InternalMessageInfo

func (m *Club) GetClubID() string {
	if m != nil {
		return m.ClubID
	}
	return ""
}

func (m *Club) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ClubUser struct {
	ClubID               string   `protobuf:"bytes,1,opt,name=clubID,proto3" json:"clubID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClubUser) Reset()         { *m = ClubUser{} }
func (m *ClubUser) String() string { return proto.CompactTextString(m) }
func (*ClubUser) ProtoMessage()    {}
func (*ClubUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{2}
}
func (m *ClubUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubUser.Unmarshal(m, b)
}
func (m *ClubUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubUser.Marshal(b, m, deterministic)
}
func (dst *ClubUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubUser.Merge(dst, src)
}
func (m *ClubUser) XXX_Size() int {
	return xxx_messageInfo_ClubUser.Size(m)
}
func (m *ClubUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubUser.DiscardUnknown(m)
}

var xxx_messageInfo_ClubUser proto.InternalMessageInfo

func (m *ClubUser) GetClubID() string {
	if m != nil {
		return m.ClubID
	}
	return ""
}

func (m *ClubUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ClubUser) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type EmailVerification struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Expiry               int64    `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailVerification) Reset()         { *m = EmailVerification{} }
func (m *EmailVerification) String() string { return proto.CompactTextString(m) }
func (*EmailVerification) ProtoMessage()    {}
func (*EmailVerification) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{3}
}
func (m *EmailVerification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerification.Unmarshal(m, b)
}
func (m *EmailVerification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerification.Marshal(b, m, deterministic)
}
func (dst *EmailVerification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerification.Merge(dst, src)
}
func (m *EmailVerification) XXX_Size() int {
	return xxx_messageInfo_EmailVerification.Size(m)
}
func (m *EmailVerification) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerification.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerification proto.InternalMessageInfo

func (m *EmailVerification) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *EmailVerification) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailVerification) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type Period struct {
	Period               string   `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{4}
}
func (m *Period) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Period.Unmarshal(m, b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Period.Marshal(b, m, deterministic)
}
func (dst *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(dst, src)
}
func (m *Period) XXX_Size() int {
	return xxx_messageInfo_Period.Size(m)
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

type EventProps struct {
	Period               string                   `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	EventID              string                   `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	Name                 string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Club                 string                   `protobuf:"bytes,4,opt,name=club,proto3" json:"club,omitempty"`
	Description          string                   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fields               []*EventProps_FieldProps `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EventProps) Reset()         { *m = EventProps{} }
func (m *EventProps) String() string { return proto.CompactTextString(m) }
func (*EventProps) ProtoMessage()    {}
func (*EventProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{5}
}
func (m *EventProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventProps.Unmarshal(m, b)
}
func (m *EventProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventProps.Marshal(b, m, deterministic)
}
func (dst *EventProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProps.Merge(dst, src)
}
func (m *EventProps) XXX_Size() int {
	return xxx_messageInfo_EventProps.Size(m)
}
func (m *EventProps) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProps.DiscardUnknown(m)
}

var xxx_messageInfo_EventProps proto.InternalMessageInfo

func (m *EventProps) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *EventProps) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func (m *EventProps) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventProps) GetClub() string {
	if m != nil {
		return m.Club
	}
	return ""
}

func (m *EventProps) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EventProps) GetFields() []*EventProps_FieldProps {
	if m != nil {
		return m.Fields
	}
	return nil
}

type EventProps_FieldProps struct {
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Required    bool   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Blurb       string `protobuf:"bytes,3,opt,name=blurb,proto3" json:"blurb,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Properties:
	//	*EventProps_FieldProps_LongText_
	//	*EventProps_FieldProps_ShortText_
	Properties           isEventProps_FieldProps_Properties `protobuf_oneof:"properties"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *EventProps_FieldProps) Reset()         { *m = EventProps_FieldProps{} }
func (m *EventProps_FieldProps) String() string { return proto.CompactTextString(m) }
func (*EventProps_FieldProps) ProtoMessage()    {}
func (*EventProps_FieldProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{5, 0}
}
func (m *EventProps_FieldProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventProps_FieldProps.Unmarshal(m, b)
}
func (m *EventProps_FieldProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventProps_FieldProps.Marshal(b, m, deterministic)
}
func (dst *EventProps_FieldProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProps_FieldProps.Merge(dst, src)
}
func (m *EventProps_FieldProps) XXX_Size() int {
	return xxx_messageInfo_EventProps_FieldProps.Size(m)
}
func (m *EventProps_FieldProps) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProps_FieldProps.DiscardUnknown(m)
}

var xxx_messageInfo_EventProps_FieldProps proto.InternalMessageInfo

func (m *EventProps_FieldProps) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventProps_FieldProps) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *EventProps_FieldProps) GetBlurb() string {
	if m != nil {
		return m.Blurb
	}
	return ""
}

func (m *EventProps_FieldProps) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type isEventProps_FieldProps_Properties interface {
	isEventProps_FieldProps_Properties()
}

type EventProps_FieldProps_LongText_ struct {
	LongText *EventProps_FieldProps_LongText `protobuf:"bytes,5,opt,name=long_text,json=longText,proto3,oneof"`
}

type EventProps_FieldProps_ShortText_ struct {
	ShortText *EventProps_FieldProps_ShortText `protobuf:"bytes,6,opt,name=short_text,json=shortText,proto3,oneof"`
}

func (*EventProps_FieldProps_LongText_) isEventProps_FieldProps_Properties() {}

func (*EventProps_FieldProps_ShortText_) isEventProps_FieldProps_Properties() {}

func (m *EventProps_FieldProps) GetProperties() isEventProps_FieldProps_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *EventProps_FieldProps) GetLongText() *EventProps_FieldProps_LongText {
	if x, ok := m.GetProperties().(*EventProps_FieldProps_LongText_); ok {
		return x.LongText
	}
	return nil
}

func (m *EventProps_FieldProps) GetShortText() *EventProps_FieldProps_ShortText {
	if x, ok := m.GetProperties().(*EventProps_FieldProps_ShortText_); ok {
		return x.ShortText
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EventProps_FieldProps) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EventProps_FieldProps_OneofMarshaler, _EventProps_FieldProps_OneofUnmarshaler, _EventProps_FieldProps_OneofSizer, []interface{}{
		(*EventProps_FieldProps_LongText_)(nil),
		(*EventProps_FieldProps_ShortText_)(nil),
	}
}

func _EventProps_FieldProps_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EventProps_FieldProps)
	// properties
	switch x := m.Properties.(type) {
	case *EventProps_FieldProps_LongText_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LongText); err != nil {
			return err
		}
	case *EventProps_FieldProps_ShortText_:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ShortText); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("EventProps_FieldProps.Properties has unexpected type %T", x)
	}
	return nil
}

func _EventProps_FieldProps_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EventProps_FieldProps)
	switch tag {
	case 5: // properties.long_text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventProps_FieldProps_LongText)
		err := b.DecodeMessage(msg)
		m.Properties = &EventProps_FieldProps_LongText_{msg}
		return true, err
	case 6: // properties.short_text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventProps_FieldProps_ShortText)
		err := b.DecodeMessage(msg)
		m.Properties = &EventProps_FieldProps_ShortText_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _EventProps_FieldProps_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EventProps_FieldProps)
	// properties
	switch x := m.Properties.(type) {
	case *EventProps_FieldProps_LongText_:
		s := proto.Size(x.LongText)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EventProps_FieldProps_ShortText_:
		s := proto.Size(x.ShortText)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EventProps_FieldProps_LongText struct {
	MaxLen               int32    `protobuf:"varint,1,opt,name=max_len,json=maxLen,proto3" json:"max_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventProps_FieldProps_LongText) Reset()         { *m = EventProps_FieldProps_LongText{} }
func (m *EventProps_FieldProps_LongText) String() string { return proto.CompactTextString(m) }
func (*EventProps_FieldProps_LongText) ProtoMessage()    {}
func (*EventProps_FieldProps_LongText) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{5, 0, 0}
}
func (m *EventProps_FieldProps_LongText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventProps_FieldProps_LongText.Unmarshal(m, b)
}
func (m *EventProps_FieldProps_LongText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventProps_FieldProps_LongText.Marshal(b, m, deterministic)
}
func (dst *EventProps_FieldProps_LongText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProps_FieldProps_LongText.Merge(dst, src)
}
func (m *EventProps_FieldProps_LongText) XXX_Size() int {
	return xxx_messageInfo_EventProps_FieldProps_LongText.Size(m)
}
func (m *EventProps_FieldProps_LongText) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProps_FieldProps_LongText.DiscardUnknown(m)
}

var xxx_messageInfo_EventProps_FieldProps_LongText proto.InternalMessageInfo

func (m *EventProps_FieldProps_LongText) GetMaxLen() int32 {
	if m != nil {
		return m.MaxLen
	}
	return 0
}

type EventProps_FieldProps_ShortText struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventProps_FieldProps_ShortText) Reset()         { *m = EventProps_FieldProps_ShortText{} }
func (m *EventProps_FieldProps_ShortText) String() string { return proto.CompactTextString(m) }
func (*EventProps_FieldProps_ShortText) ProtoMessage()    {}
func (*EventProps_FieldProps_ShortText) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{5, 0, 1}
}
func (m *EventProps_FieldProps_ShortText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventProps_FieldProps_ShortText.Unmarshal(m, b)
}
func (m *EventProps_FieldProps_ShortText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventProps_FieldProps_ShortText.Marshal(b, m, deterministic)
}
func (dst *EventProps_FieldProps_ShortText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProps_FieldProps_ShortText.Merge(dst, src)
}
func (m *EventProps_FieldProps_ShortText) XXX_Size() int {
	return xxx_messageInfo_EventProps_FieldProps_ShortText.Size(m)
}
func (m *EventProps_FieldProps_ShortText) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProps_FieldProps_ShortText.DiscardUnknown(m)
}

var xxx_messageInfo_EventProps_FieldProps_ShortText proto.InternalMessageInfo

type Applicant struct {
	Period               string   `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Applicant) Reset()         { *m = Applicant{} }
func (m *Applicant) String() string { return proto.CompactTextString(m) }
func (*Applicant) ProtoMessage()    {}
func (*Applicant) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{6}
}
func (m *Applicant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Applicant.Unmarshal(m, b)
}
func (m *Applicant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Applicant.Marshal(b, m, deterministic)
}
func (dst *Applicant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Applicant.Merge(dst, src)
}
func (m *Applicant) XXX_Size() int {
	return xxx_messageInfo_Applicant.Size(m)
}
func (m *Applicant) XXX_DiscardUnknown() {
	xxx_messageInfo_Applicant.DiscardUnknown(m)
}

var xxx_messageInfo_Applicant proto.InternalMessageInfo

func (m *Applicant) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Applicant) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Applicant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Applicant) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Application struct {
	Period               string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	EventID              string                 `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Entries              map[string]*FieldEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{7}
}
func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (dst *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(dst, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Application) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func (m *Application) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetEntries() map[string]*FieldEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type FieldEntry struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldEntry) Reset()         { *m = FieldEntry{} }
func (m *FieldEntry) String() string { return proto.CompactTextString(m) }
func (*FieldEntry) ProtoMessage()    {}
func (*FieldEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{8}
}
func (m *FieldEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldEntry.Unmarshal(m, b)
}
func (m *FieldEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldEntry.Marshal(b, m, deterministic)
}
func (dst *FieldEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldEntry.Merge(dst, src)
}
func (m *FieldEntry) XXX_Size() int {
	return xxx_messageInfo_FieldEntry.Size(m)
}
func (m *FieldEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FieldEntry proto.InternalMessageInfo

func (m *FieldEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Tag struct {
	Period               string   `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	TagName              string   `protobuf:"bytes,2,opt,name=tagName,proto3" json:"tagName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_dbed86013addef5c, []int{9}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Tag) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "models.User")
	proto.RegisterType((*Club)(nil), "models.Club")
	proto.RegisterType((*ClubUser)(nil), "models.ClubUser")
	proto.RegisterType((*EmailVerification)(nil), "models.EmailVerification")
	proto.RegisterType((*Period)(nil), "models.Period")
	proto.RegisterType((*EventProps)(nil), "models.EventProps")
	proto.RegisterType((*EventProps_FieldProps)(nil), "models.EventProps.FieldProps")
	proto.RegisterType((*EventProps_FieldProps_LongText)(nil), "models.EventProps.FieldProps.LongText")
	proto.RegisterType((*EventProps_FieldProps_ShortText)(nil), "models.EventProps.FieldProps.ShortText")
	proto.RegisterType((*Applicant)(nil), "models.Applicant")
	proto.RegisterType((*Application)(nil), "models.Application")
	proto.RegisterMapType((map[string]*FieldEntry)(nil), "models.Application.EntriesEntry")
	proto.RegisterType((*FieldEntry)(nil), "models.FieldEntry")
	proto.RegisterType((*Tag)(nil), "models.Tag")
}

func init() { proto.RegisterFile("models/models.proto", fileDescriptor_models_dbed86013addef5c) }

var fileDescriptor_models_dbed86013addef5c = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xb1, 0xe3, 0x3a, 0x93, 0x1e, 0x60, 0xa9, 0x8a, 0x15, 0x09, 0xc9, 0x32, 0x12, 0xe4,
	0x94, 0xa0, 0x20, 0x04, 0xea, 0x09, 0x4a, 0x83, 0x5a, 0xa9, 0xaa, 0x2a, 0xd3, 0x72, 0xe0, 0x52,
	0xd6, 0xf6, 0x36, 0x59, 0xb1, 0xf1, 0x9a, 0xf5, 0xba, 0x4a, 0x7f, 0x01, 0xbf, 0x8c, 0x9f, 0xc4,
	0x1d, 0xed, 0x87, 0x5d, 0xd3, 0x36, 0x95, 0x38, 0x79, 0xde, 0x78, 0xf6, 0xcd, 0xdb, 0xb7, 0xa3,
	0x81, 0xa7, 0x2b, 0x9e, 0x13, 0x56, 0x4d, 0xcd, 0x67, 0x52, 0x0a, 0x2e, 0x39, 0xf2, 0x0d, 0x8a,
	0xbf, 0x83, 0x77, 0x5e, 0x11, 0x81, 0x76, 0xa0, 0x4f, 0x56, 0x98, 0xb2, 0xd0, 0x89, 0x9c, 0xf1,
	0x20, 0x31, 0x00, 0x21, 0xf0, 0x0a, 0xbc, 0x22, 0x61, 0x4f, 0x27, 0x75, 0xac, 0x72, 0x4b, 0x5c,
	0x2d, 0x43, 0xd7, 0xe4, 0x54, 0x8c, 0x46, 0x10, 0x5c, 0x11, 0x41, 0x2f, 0x29, 0xc9, 0x43, 0x2f,
	0x72, 0xc6, 0x41, 0xd2, 0xe2, 0xf8, 0x03, 0x78, 0x9f, 0x58, 0x9d, 0xa2, 0x5d, 0xf0, 0x33, 0x56,
	0xa7, 0x47, 0x07, 0xb6, 0x85, 0x45, 0x28, 0x82, 0x61, 0x4e, 0xaa, 0x4c, 0xd0, 0x52, 0x52, 0x5e,
	0xd8, 0x56, 0xdd, 0x54, 0x7c, 0x0c, 0x81, 0x62, 0xd0, 0x3a, 0x37, 0xb1, 0xb4, 0xfa, 0x7b, 0xb7,
	0xf4, 0x0b, 0xce, 0x48, 0xa3, 0x55, 0xc5, 0xf1, 0x39, 0x3c, 0x99, 0xab, 0x9f, 0x5f, 0xb5, 0xc0,
	0x0c, 0xab, 0x16, 0xed, 0xa5, 0x9c, 0xce, 0xa5, 0xee, 0xa7, 0xdc, 0x05, 0x9f, 0xac, 0x4b, 0x2a,
	0xae, 0x35, 0xa9, 0x9b, 0x58, 0x14, 0x47, 0xe0, 0x9f, 0x12, 0x41, 0x79, 0xae, 0x2a, 0x4a, 0x1d,
	0x35, 0x12, 0x0d, 0x8a, 0x7f, 0x79, 0x00, 0xf3, 0x2b, 0x52, 0xc8, 0x53, 0xc1, 0xcb, 0x6a, 0x53,
	0x19, 0x0a, 0x61, 0x8b, 0xa8, 0xaa, 0xa3, 0x03, 0xdb, 0xb8, 0x81, 0xed, 0x6b, 0xb8, 0xff, 0xbe,
	0x86, 0x72, 0x40, 0xbb, 0x3e, 0x48, 0x74, 0x7c, 0xdb, 0xd1, 0xfe, 0x1d, 0x47, 0xd1, 0x5b, 0xf0,
	0x2f, 0x29, 0x61, 0x79, 0x15, 0xfa, 0x91, 0x3b, 0x1e, 0xce, 0x9e, 0x4f, 0xec, 0x70, 0xdc, 0xe8,
	0x9b, 0x7c, 0x56, 0x05, 0x3a, 0x4c, 0x6c, 0xf1, 0xe8, 0x77, 0x0f, 0xe0, 0x26, 0xdd, 0xea, 0x71,
	0x3a, 0x7a, 0x46, 0x10, 0x08, 0xf2, 0xb3, 0xa6, 0x82, 0xe4, 0x5a, 0x7e, 0x90, 0xb4, 0x58, 0x19,
	0x9a, 0xb2, 0x5a, 0xa4, 0xf6, 0x02, 0x06, 0xdc, 0x56, 0xeb, 0xdd, 0x55, 0x3b, 0x87, 0x01, 0xe3,
	0xc5, 0xe2, 0x42, 0x92, 0xb5, 0xd4, 0xb7, 0x19, 0xce, 0x5e, 0x3e, 0x28, 0x78, 0x72, 0xcc, 0x8b,
	0xc5, 0x19, 0x59, 0xcb, 0xc3, 0x47, 0x49, 0xc0, 0x6c, 0x8c, 0x0e, 0x01, 0xaa, 0x25, 0x17, 0xd2,
	0xf0, 0xf8, 0x9a, 0xe7, 0xd5, 0xc3, 0x3c, 0x5f, 0x54, 0xbd, 0x25, 0x1a, 0x54, 0x0d, 0x18, 0xbd,
	0x80, 0xa0, 0xe9, 0x80, 0x9e, 0xc1, 0xd6, 0x0a, 0xaf, 0x2f, 0x18, 0x29, 0xb4, 0x0f, 0xfd, 0xc4,
	0x5f, 0xe1, 0xf5, 0x31, 0x29, 0x46, 0x43, 0x18, 0xb4, 0xc7, 0xf7, 0xb7, 0x01, 0x4a, 0xc1, 0x4b,
	0x22, 0x24, 0x25, 0x55, 0x8c, 0x61, 0xf0, 0xb1, 0x2c, 0x19, 0xcd, 0x70, 0x21, 0x37, 0xce, 0xc1,
	0xc6, 0x89, 0xbe, 0x6f, 0x06, 0x24, 0x5e, 0x54, 0xa1, 0x17, 0xb9, 0x2a, 0xa7, 0xe2, 0xf8, 0x8f,
	0x03, 0x43, 0xdb, 0x43, 0x7b, 0xf8, 0xff, 0xd3, 0xd6, 0xf6, 0x77, 0xef, 0xeb, 0xef, 0x75, 0xfa,
	0xef, 0xc1, 0x16, 0x29, 0xa4, 0xa0, 0xa4, 0x0a, 0xfb, 0x7a, 0x9c, 0xa2, 0xc6, 0xd5, 0x8e, 0x82,
	0xc9, 0xdc, 0x94, 0xa8, 0xcf, 0x75, 0xd2, 0x1c, 0x18, 0x9d, 0xc0, 0x76, 0xf7, 0x07, 0x7a, 0x0c,
	0xee, 0x0f, 0x72, 0x6d, 0x45, 0xaa, 0x10, 0x8d, 0xa1, 0x7f, 0x85, 0x59, 0x6d, 0x96, 0xd0, 0x70,
	0x86, 0x1a, 0x6e, 0xfd, 0x4c, 0x86, 0xcd, 0x14, 0xec, 0xf5, 0xde, 0x3b, 0x71, 0x6c, 0x27, 0xd4,
	0xb0, 0xed, 0x34, 0x67, 0x15, 0xdf, 0xb6, 0xad, 0x8b, 0xdf, 0x81, 0x7b, 0x86, 0x17, 0x0f, 0x59,
	0x22, 0xf1, 0xe2, 0xe4, 0x66, 0xef, 0x35, 0x70, 0x7f, 0xf6, 0xed, 0xf5, 0x82, 0xca, 0x65, 0x9d,
	0x4e, 0x32, 0xbe, 0x9a, 0xd6, 0x69, 0xc6, 0x70, 0x5d, 0x64, 0xcb, 0x12, 0xe7, 0xd3, 0x92, 0x16,
	0x25, 0xa7, 0x85, 0x9c, 0xea, 0xf5, 0x9a, 0xd6, 0x97, 0x76, 0xdd, 0xa6, 0xbe, 0x4e, 0xbc, 0xf9,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x82, 0xe1, 0x44, 0x0c, 0x86, 0x05, 0x00, 0x00,
}
