// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/models.proto

package models // import "github.com/ubclaunchpad/pinpoint/protobuf/models"

/*
package model defines model datatypes
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Period               string   `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	EventID              string   `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Fields               []*Field `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_0e3115d339ecf51c, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Event) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Field struct {
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Required bool   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	// Types that are valid to be assigned to Properties:
	//	*Field_LongText
	//	*Field_ShortText
	Properties           isField_Properties `protobuf_oneof:"properties"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_0e3115d339ecf51c, []int{1}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (dst *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(dst, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

type isField_Properties interface {
	isField_Properties()
}

type Field_LongText struct {
	LongText *LongText `protobuf:"bytes,3,opt,name=long_text,json=longText,proto3,oneof"`
}

type Field_ShortText struct {
	ShortText *ShortText `protobuf:"bytes,4,opt,name=short_text,json=shortText,proto3,oneof"`
}

func (*Field_LongText) isField_Properties() {}

func (*Field_ShortText) isField_Properties() {}

func (m *Field) GetProperties() isField_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Field) GetLongText() *LongText {
	if x, ok := m.GetProperties().(*Field_LongText); ok {
		return x.LongText
	}
	return nil
}

func (m *Field) GetShortText() *ShortText {
	if x, ok := m.GetProperties().(*Field_ShortText); ok {
		return x.ShortText
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Field) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Field_OneofMarshaler, _Field_OneofUnmarshaler, _Field_OneofSizer, []interface{}{
		(*Field_LongText)(nil),
		(*Field_ShortText)(nil),
	}
}

func _Field_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Field)
	// properties
	switch x := m.Properties.(type) {
	case *Field_LongText:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LongText); err != nil {
			return err
		}
	case *Field_ShortText:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ShortText); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Field.Properties has unexpected type %T", x)
	}
	return nil
}

func _Field_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Field)
	switch tag {
	case 3: // properties.long_text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LongText)
		err := b.DecodeMessage(msg)
		m.Properties = &Field_LongText{msg}
		return true, err
	case 4: // properties.short_text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ShortText)
		err := b.DecodeMessage(msg)
		m.Properties = &Field_ShortText{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Field_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Field)
	// properties
	switch x := m.Properties.(type) {
	case *Field_LongText:
		s := proto.Size(x.LongText)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Field_ShortText:
		s := proto.Size(x.ShortText)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LongText struct {
	ImLong               string   `protobuf:"bytes,1,opt,name=im_long,json=imLong,proto3" json:"im_long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongText) Reset()         { *m = LongText{} }
func (m *LongText) String() string { return proto.CompactTextString(m) }
func (*LongText) ProtoMessage()    {}
func (*LongText) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_0e3115d339ecf51c, []int{2}
}
func (m *LongText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongText.Unmarshal(m, b)
}
func (m *LongText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongText.Marshal(b, m, deterministic)
}
func (dst *LongText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongText.Merge(dst, src)
}
func (m *LongText) XXX_Size() int {
	return xxx_messageInfo_LongText.Size(m)
}
func (m *LongText) XXX_DiscardUnknown() {
	xxx_messageInfo_LongText.DiscardUnknown(m)
}

var xxx_messageInfo_LongText proto.InternalMessageInfo

func (m *LongText) GetImLong() string {
	if m != nil {
		return m.ImLong
	}
	return ""
}

type ShortText struct {
	ImShort              string   `protobuf:"bytes,1,opt,name=im_short,json=imShort,proto3" json:"im_short,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortText) Reset()         { *m = ShortText{} }
func (m *ShortText) String() string { return proto.CompactTextString(m) }
func (*ShortText) ProtoMessage()    {}
func (*ShortText) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_0e3115d339ecf51c, []int{3}
}
func (m *ShortText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortText.Unmarshal(m, b)
}
func (m *ShortText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortText.Marshal(b, m, deterministic)
}
func (dst *ShortText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortText.Merge(dst, src)
}
func (m *ShortText) XXX_Size() int {
	return xxx_messageInfo_ShortText.Size(m)
}
func (m *ShortText) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortText.DiscardUnknown(m)
}

var xxx_messageInfo_ShortText proto.InternalMessageInfo

func (m *ShortText) GetImShort() string {
	if m != nil {
		return m.ImShort
	}
	return ""
}

type Applicant struct {
	Period               string   `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Applicant) Reset()         { *m = Applicant{} }
func (m *Applicant) String() string { return proto.CompactTextString(m) }
func (*Applicant) ProtoMessage()    {}
func (*Applicant) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_0e3115d339ecf51c, []int{4}
}
func (m *Applicant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Applicant.Unmarshal(m, b)
}
func (m *Applicant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Applicant.Marshal(b, m, deterministic)
}
func (dst *Applicant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Applicant.Merge(dst, src)
}
func (m *Applicant) XXX_Size() int {
	return xxx_messageInfo_Applicant.Size(m)
}
func (m *Applicant) XXX_DiscardUnknown() {
	xxx_messageInfo_Applicant.DiscardUnknown(m)
}

var xxx_messageInfo_Applicant proto.InternalMessageInfo

func (m *Applicant) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Applicant) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Applicant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Applicant) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Application struct {
	Period               string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	EventID              string                 `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Entries              map[string]*FieldEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_0e3115d339ecf51c, []int{5}
}
func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (dst *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(dst, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Application) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func (m *Application) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetEntries() map[string]*FieldEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type FieldEntry struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldEntry) Reset()         { *m = FieldEntry{} }
func (m *FieldEntry) String() string { return proto.CompactTextString(m) }
func (*FieldEntry) ProtoMessage()    {}
func (*FieldEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_0e3115d339ecf51c, []int{6}
}
func (m *FieldEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldEntry.Unmarshal(m, b)
}
func (m *FieldEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldEntry.Marshal(b, m, deterministic)
}
func (dst *FieldEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldEntry.Merge(dst, src)
}
func (m *FieldEntry) XXX_Size() int {
	return xxx_messageInfo_FieldEntry.Size(m)
}
func (m *FieldEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FieldEntry proto.InternalMessageInfo

func (m *FieldEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Tag struct {
	Period               string   `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	TagName              string   `protobuf:"bytes,2,opt,name=tagName,proto3" json:"tagName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_0e3115d339ecf51c, []int{7}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Tag) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "models.Event")
	proto.RegisterType((*Field)(nil), "models.Field")
	proto.RegisterType((*LongText)(nil), "models.LongText")
	proto.RegisterType((*ShortText)(nil), "models.ShortText")
	proto.RegisterType((*Applicant)(nil), "models.Applicant")
	proto.RegisterType((*Application)(nil), "models.Application")
	proto.RegisterMapType((map[string]*FieldEntry)(nil), "models.Application.EntriesEntry")
	proto.RegisterType((*FieldEntry)(nil), "models.FieldEntry")
	proto.RegisterType((*Tag)(nil), "models.Tag")
}

func init() { proto.RegisterFile("models/models.proto", fileDescriptor_models_0e3115d339ecf51c) }

var fileDescriptor_models_0e3115d339ecf51c = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x25, 0x4d, 0xb2, 0x9b, 0x4c, 0x16, 0xa9, 0x18, 0x04, 0xa1, 0xa7, 0x28, 0x08, 0xb4, 0xa7,
	0x0d, 0x0a, 0x07, 0x50, 0x6f, 0x54, 0x14, 0x81, 0x84, 0x7a, 0x08, 0x3d, 0x71, 0x59, 0x79, 0x93,
	0x69, 0xd6, 0x22, 0x89, 0x4d, 0xe2, 0x54, 0xed, 0x8f, 0xf0, 0x11, 0xfc, 0x1f, 0x77, 0x64, 0xc7,
	0x5e, 0x82, 0x54, 0x55, 0xe2, 0xe4, 0x79, 0xf3, 0x66, 0xe6, 0x8d, 0x67, 0x6c, 0x78, 0xdc, 0xf2,
	0x0a, 0x9b, 0x21, 0x9b, 0x8e, 0x8d, 0xe8, 0xb9, 0xe4, 0x64, 0x31, 0xa1, 0xf4, 0xa7, 0x03, 0xfe,
	0xf9, 0x35, 0x76, 0x92, 0x3c, 0x85, 0x85, 0xc0, 0x9e, 0xf1, 0x2a, 0x76, 0x12, 0x67, 0x1d, 0x16,
	0x06, 0x91, 0x18, 0x96, 0xa8, 0x02, 0x3e, 0x7f, 0x88, 0x8f, 0x34, 0x61, 0x21, 0x21, 0xe0, 0x75,
	0xb4, 0xc5, 0xd8, 0xd5, 0x6e, 0x6d, 0x93, 0x04, 0xa2, 0x0a, 0x87, 0xb2, 0x67, 0x42, 0x32, 0xde,
	0xc5, 0x9e, 0xa6, 0xe6, 0x2e, 0xf2, 0x12, 0x16, 0x57, 0x0c, 0x9b, 0x6a, 0x88, 0xfd, 0xc4, 0x5d,
	0x47, 0xf9, 0xc3, 0x8d, 0x69, 0xec, 0xa3, 0xf2, 0x16, 0x86, 0x4c, 0x7f, 0x39, 0xe0, 0x6b, 0xcf,
	0x41, 0xc6, 0x99, 0xc9, 0x9c, 0x40, 0xd0, 0xe3, 0x8f, 0x91, 0xf5, 0x58, 0xe9, 0xae, 0x82, 0xe2,
	0x80, 0x49, 0x06, 0x61, 0xc3, 0xbb, 0x7a, 0x2b, 0xf1, 0x46, 0xea, 0xde, 0xa2, 0xfc, 0xd8, 0x6a,
	0x7c, 0xe1, 0x5d, 0x7d, 0x89, 0x37, 0xf2, 0xd3, 0x83, 0x22, 0x68, 0x8c, 0x4d, 0x72, 0x80, 0x61,
	0xcf, 0x7b, 0x39, 0x65, 0x78, 0x3a, 0xe3, 0x91, 0xcd, 0xf8, 0xaa, 0x18, 0x93, 0x12, 0x0e, 0x16,
	0x9c, 0xad, 0x00, 0x44, 0xcf, 0x05, 0xf6, 0x92, 0xe1, 0x90, 0xbe, 0x80, 0xc0, 0x56, 0x26, 0xcf,
	0x60, 0xc9, 0xda, 0xad, 0x2a, 0x6e, 0x07, 0xc9, 0x5a, 0x45, 0xa6, 0xaf, 0x20, 0x3c, 0x14, 0x23,
	0xcf, 0x21, 0x60, 0xed, 0x56, 0xd7, 0x33, 0x61, 0x4b, 0xd6, 0x6a, 0x3a, 0xa5, 0x10, 0xbe, 0x17,
	0xa2, 0x61, 0x25, 0xbd, 0x67, 0x2b, 0x4f, 0xc0, 0xc7, 0x96, 0xb2, 0xc6, 0xec, 0x64, 0x02, 0x77,
	0x6e, 0x84, 0x80, 0x27, 0x69, 0x3d, 0xc4, 0x5e, 0xe2, 0x2a, 0x9f, 0xb2, 0xd3, 0xdf, 0x0e, 0x44,
	0x46, 0x43, 0xef, 0xe4, 0xff, 0x77, 0x7f, 0xd0, 0x77, 0xef, 0xd2, 0xf7, 0x66, 0xfa, 0xa7, 0xb0,
	0xc4, 0x4e, 0xf6, 0x0c, 0xed, 0xc2, 0x13, 0x3b, 0xda, 0x59, 0x07, 0x9b, 0xf3, 0x29, 0x44, 0x1d,
	0xb7, 0x85, 0x4d, 0x38, 0xb9, 0x80, 0xd5, 0x9c, 0x20, 0xc7, 0xe0, 0x7e, 0xc7, 0x5b, 0xd3, 0xa4,
	0x32, 0xc9, 0x1a, 0xfc, 0x6b, 0xda, 0x8c, 0xa8, 0xfb, 0x8b, 0x72, 0xf2, 0xcf, 0x63, 0x9a, 0xaa,
	0x4d, 0x01, 0xa7, 0x47, 0xef, 0x9c, 0x34, 0x05, 0xf8, 0x4b, 0xa8, 0x3b, 0x4c, 0xb9, 0xaa, 0xde,
	0xca, 0xc4, 0xa5, 0x6f, 0xc1, 0xbd, 0xa4, 0xf5, 0x7d, 0x23, 0x91, 0xb4, 0xbe, 0x50, 0xb7, 0x34,
	0x23, 0x31, 0xf0, 0x2c, 0xff, 0xf6, 0xba, 0x66, 0x72, 0x3f, 0xee, 0x36, 0x25, 0x6f, 0xb3, 0x71,
	0x57, 0x36, 0x74, 0xec, 0xca, 0xbd, 0xa0, 0x55, 0x26, 0x58, 0x27, 0x38, 0xeb, 0x64, 0xa6, 0x3f,
	0xdf, 0x6e, 0xbc, 0x32, 0x9f, 0x71, 0xb7, 0xd0, 0x8e, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x45, 0x11, 0x27, 0x59, 0xa4, 0x03, 0x00, 0x00,
}
